apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dump-procio
spec:
  selector:
    matchLabels:
      component: ds-dump-procio
  template:
    metadata:
      labels:
        component: ds-dump-procio
    spec:
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: ''
      - name: volume
        persistentVolumeClaim:
          claimName: my-azurefile
      containers:
      - command:
        - sh
        - -c
        - |
          apt-get update && apt-get install -y iotop;chroot /host iotop -Pbot -d 10 > /data/iotop-$(hostname).log
        image: ubuntu
        name: procio
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: volume
          mountPath: /data
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
      hostNetwork: true
      hostPID: true
      hostIPC: true
