apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msdiag-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi-premium
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: check-mem
  name: check-mem
spec:
  selector:
    matchLabels:
      component: ds-check-mem
  template:
    metadata:
      labels:
        component: ds-check-mem
    spec:
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: msdiag-azurefile
      containers:
      - command:
        - bash
        - -c
        - |
          apt-get update && apt-get install -y procps;
          while true;do date >> /mnt/azfile/ps-$(hostname).log;ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head >> /mnt/azfile/ps-$(hostname).log;echo;sleep 10;done
        image: mcr.microsoft.com/mirror/docker/library/debian:bullseye-slim
        name: utility
        volumeMounts:
        - name: volume
          mountPath: /mnt/azfile      
      hostNetwork: true
      hostPID: true
      hostIPC: true
