apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: check-mem
  name: check-mem
spec:
  selector:
    matchLabels:
      component: ds-check-mem
  template:
    metadata:
      labels:
        component: ds-check-mem
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - command:
        - bash
        - -c
        - |          
          while true;do date;
          ps -eo pmem,pcpu,vsize,pid,cmd | sort -k 2 -nr | head -5;
          echo; sleep 10; done
        image: ubuntu
        name: utility
