apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: ds-set-pidmax
  name: set-pidmax
spec:
  selector:
    matchLabels:
      component: ds-set-pidmax
  template:
    metadata:
      labels:
        component: ds-set-pidmax
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - volumeMounts:
        - name: host-root
          mountPath: /host
        command:
        - bash
        - -c
        - |
          chroot /host echo "250000" > /proc/sys/kernel/pid_max
          sleep infinity
        image: alpine
        name: sysctl-patch
    volumes:
      - name: host-root
        hostPath:
          path: /
          type: ''