apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
data:
  .dockerconfigjson: >-
    <Base64EncOfDockerCfg:{"auths":{"acr758933.azurecr.io":{"username":...,"password":[acrCredential],"auth":[authStr]}}}>
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Pod
metadata:
  name: my-awesome-app-pod
spec:
  containers:
    - name: main-app-container
      image: acr758933.azurecr.io/wordpress:test
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: acr-secret
