apiVersion: apps/v1
kind: Deployment
metadata:
  name: david-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworldcdsdfsdfkkk
  template:
    metadata:
      labels:
        app: aci-helloworldcdsdfsdfkkk
    spec:
      containers:
      - name: aci-helloworldabcdd
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
