apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: netcat-probe
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: 
    - /bin/bash
    args:
    - -c
    - apt-get update;apt-get install -y netcat; while true; do netcat -zv 3.0.45.135 443; sleep 3; done
  nodeSelector:
    kubernetes.io/hostname: aks-master2-28878595-vmss000000
