# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Public

on:
  workflow_dispatch

jobs:
  release-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Create release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        commit: master
        tag: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        name: ${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      releaseId: ${{ steps.create_release.outputs.id }}
  build:
    needs: release-setup
    strategy:
      max-parallel: 1
      matrix:
        source_info: ['ondrajz/go-callvis,"go build",go-callvis,.','mosajjal/dnsmonster,"go build",dnsmonster,cmd/dnsmonster','cyberelf/netcat-keepalive,"make linux",nckl-linux,.']
    runs-on: ubuntu-latest
    steps:
    - uses: jungwinter/split@master
      id: split
      with:
        msg: ${{ matrix.source_info }}
        separator: ","
        maxsplit: -1
    - uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: libpcap0.8-dev libssl-dev libldns-dev libck-dev libnghttp2-dev
    - uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: ${{ steps.split.outputs._0 }}
        path: ${{ steps.split.outputs._0 }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build
      run: |
        cd ${{ steps.split.outputs._0 }}/${{ steps.split.outputs._3 }}
        bash -c ${{ steps.split.outputs._1 }}
        mv ${{ steps.split.outputs._2 }} ${{ steps.split.outputs._2 }}-linux-amd64
    - name: Upload assets
      uses: xresloader/upload-to-github-release@v1.3.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release-setup.outputs.releaseId }}
        file: ${{ steps.split.outputs._0 }}/${{ steps.split.outputs._3 }}/${{ steps.split.outputs._2 }}-linux-amd64
        draft: false
