name: GraphRAG Index

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Public repository URL to clone'
        required: true
        default: 'https://github.com/example/repo'
      knowledge_pack_name:
        description: 'The topic of the released knowedge pack'
        required: true        

jobs:
  release-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Create release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        commit: graphrag
        tag: pack-${{ inputs.knowledge_pack_name }}_${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        name: pack-${{ inputs.knowledge_pack_name }}_${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      releaseId: ${{ steps.create_release.outputs.id }}
  run-python-script:
    needs: release-setup
    runs-on: ubuntu-latest
    environment: "AOAI"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with: 
        ref: 'graphrag'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir graphrag pandas

    - name: Clone Public Repository
      run: git clone ${{ github.event.inputs.repo_url }} input/

    - name: Graphrag init
      run: graphrag init

    - name: Format config file
      run: |
        awk '{gsub("{{model_deploy}}","${{ vars.MODEL_DEPLOY }}")}1' config/settings.yaml > config/tmp && mv config/tmp config/settings.yaml
        awk '{gsub("{{api_base}}","${{ vars.MODEL_BASE }}")}1' config/settings.yaml > config/tmp && mv config/tmp config/settings.yaml
        awk '{gsub("{{api_key}}","${{ secrets.AOAI_KEY }}")}1' config/settings.yaml > config/tmp && mv config/tmp config/settings.yaml
        awk '{gsub("{{chunk_size}}","${{ vars.CHUNK_SIZE }}")}1' config/settings.yaml > config/tmp && mv config/tmp config/settings.yaml
        mv config/settings.yaml ./
    
    - name: Run prompt auto-tune
      run: graphrag prompt-tune -c settings.yaml

    - name: Run index
      run: graphrag index -c settings.yaml --method fast

    - name: zip the knowledge pack
      run: zip -r pack-${{ inputs.knowledge_pack_name }}.zip prompts/ output/

    - name: Upload assets
      uses: xresloader/upload-to-github-release@v1.3.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release-setup.outputs.releaseId }}
        file: pack-${{ inputs.knowledge_pack_name }}.zip
        draft: false    
      
